# Generated by Django 5.0.6 on 2024-06-06 12:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='barangay',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='house_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(choices=[('RC', 'Roman Catholic'), ('BC', 'Bornagain Christian'), ('M', 'Muslim')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='zip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
