# Generated by Django 5.0.6 on 2024-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('TP', 'Temporary'), ('IT', 'Internship')], max_length=2)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.CharField(choices=[('Semi', 'Semi-Monthly'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly')], max_length=20),
        ),
    ]
