# Generated by Django 5.0.6 on 2024-06-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='employee_images/'),
        ),
    ]
