# Generated by Django 5.0.6 on 2024-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_contract_employee_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
